# Generated by Django 6.0.5 on 2026-05-18 11:11

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_blood_type', models.CharField(choices=[('DEA 1.1+', 'DEA 1.1+'), ('DEA 1.1-', 'DEA 1.1-'), ('DEA 1.2+', 'DEA 1.2+'), ('DEA 1.2-', 'DEA 1.2-'), ('DEA 3', 'DEA 3'), ('DEA 4', 'DEA 4'), ('DEA 7', 'DEA 7')], max_length=10)),
                ('quantity_required', models.PositiveIntegerField()),
                ('urgency_level', models.CharField(choices=[('Routine', 'Routine'), ('Emergency', 'Emergency')], max_length=10)),
                ('required_date', models.DateField()),
                ('additional_clinical_notes', models.TextField(blank=True, max_length=500)),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('postcode', models.CharField(blank=True, max_length=4)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DogDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('blood_type', models.CharField(blank=True, choices=[('DEA 1.1+', 'DEA 1.1+'), ('DEA 1.1-', 'DEA 1.1-'), ('DEA 1.2+', 'DEA 1.2+'), ('DEA 1.2-', 'DEA 1.2-'), ('DEA 3', 'DEA 3'), ('DEA 4', 'DEA 4'), ('DEA 7', 'DEA 7'), ('Unknown', 'Unknown')], max_length=10)),
                ('vaccination_status', models.BooleanField(default=False)),
                ('health_declaration', models.BooleanField(default=False)),
                ('health_status', models.CharField(blank=True, max_length=200)),
                ('eligibility_status', models.CharField(choices=[('Eligible', 'Eligible'), ('Temporarily Ineligible', 'Temporarily Ineligible'), ('Permanently Ineligible', 'Permanently Ineligible'), ('Pending', 'Pending')], default='Pending', max_length=30)),
                ('next_eligible_date', models.DateField(blank=True, null=True)),
                ('suspension_status', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonorClinicMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_confirmation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('match_status', models.CharField(choices=[('Proposed', 'Proposed'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Proposed', max_length=10)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dogdonor')),
                ('matched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blooddonationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_status', models.CharField(choices=[('Eligible', 'Eligible'), ('Temporarily Ineligible', 'Temporarily Ineligible'), ('Permanently Ineligible', 'Permanently Ineligible')], max_length=30)),
                ('assessment_date', models.DateField()),
                ('reason_for_ineligibility', models.TextField(blank=True)),
                ('next_eligible_date', models.DateField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dogdonor')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
                ('policy_description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Selected', 'Selected for Donation'), ('Outcome', 'Donation Outcome')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
                ('related_dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dogdonor')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blooddonationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_donor_registrations', models.BooleanField(default=False)),
                ('manage_eligibility_assessments', models.BooleanField(default=False)),
                ('manage_donation_requests', models.BooleanField(default=False)),
                ('perform_donor_clinic_matching', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VeterinaryClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=100)),
                ('clinic_contact_details', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blooddonationrequest',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veterinaryclinic'),
        ),
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('volume_donated', models.PositiveIntegerField()),
                ('post_donation_notes', models.TextField(blank=True, max_length=500)),
                ('recovery_period_end_date', models.DateField()),
                ('donation_outcome', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Incomplete', 'Incomplete'), ('Cancelled', 'Cancelled')], max_length=15)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blooddonationrequest')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dogdonor')),
                ('receiving_clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.veterinaryclinic')),
            ],
        ),
    ]
