# Generated by Django 6.0.5 on 2026-05-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eligibilitypolicy',
            options={'verbose_name': 'EligibilityPolicy', 'verbose_name_plural': 'EligibilityPolicy'},
        ),
        migrations.AlterModelOptions(
            name='staffpermission',
            options={'verbose_name': 'StaffPermission', 'verbose_name_plural': 'StaffPermission'},
        ),
    ]
